### PR TITLE
Typo in GameRules for mobGriefing

### PR DESCRIPTION
**Pull request by kvgeorge1**
Checking for gamerule MobGriefing was failing because the rule is called 'doMobGriefing' but the server was looking at 'mobGriefing'

### CODE REVIEW

**Comment by CodeCrafter47** [comment]
This should also be fixed in setGameRule()

**Comment by kvgeorge1** [comment]
Corrected all other source code.

**Comment by CodeCrafter47** [comment]
Um, according to the minecraft wiki it is called mobGriefing not doMobGriefing: http://minecraft.gamepedia.com/Gamerule#gamerule

**Comment by kvgeorge1** [comment]
Holy Cow!  You are right!

So, here is what is happening....

When I was using the PluginReference to get the game mode for 
"MC_GameRuleType.MOB_GRIEFING", the result would ALWAYS come back false, 
no matter what the rule was set to.  When I did a direct call using the 
server.jar directly, and used gameRule value of "doMobGriefing", it was 
come back true if I had set "/gamerule doMobGriefing true" and false if 
I did "/gamerule doMobGriefing false".

So, my question is:

Is the Wiki incorrect, the code incorrect, or something else going on.  
This behavior is noticed in the un-patched version of the .jar as well.

**Comment by CodeCrafter47** [comment]
The wiki is correct. That's what we have a wiki for.

Also the mobGriefing gamerule works fine with the MultiWorld plugin.

**Comment by CodeCrafter47** [comment]
I tested it. MC_World.getGameRuleBool() works correctly for the mobGriefing gamerule. It reflects changes I make through the /gamerule command as well as changes made by the MultiWorld plugin.

**Comment by kvgeorge1** [comment]
Hmmm....

Ok, I will revert my changes and cancel the request.  I need to know WHY 
getGameRule(MC_GameRuleType.MOB_GRIEFING) is failing no matter what the 
rule is set to in my plugins and tests.

What is the best-way to revert a push?

**Pull request closed without merging**
